site_name: ficus 

pages:
    - Home: index.md
    - Features: features.md

site_url: https://ficus.markgemmill.com
repo_url: https://bitbucket.org/mgemmill/ficus
site_description: INI configuration library
site_author: Mark Gemmill
copyright: 2017 Mark Gemmill
use_directory_urls: true

theme: alabaster

theme_dir: custom_theme

extra_css:
    - css/highlight.css

extra_javascript:
    - js/highlight.pack.js

extra:
    logo_name: foo
    logo_title: foo-title
    #extra_nav_links:   
        #Fork me on GitHub: https://bitbucket.org/mgemmill/ficus
    homepage_sidebars: [about, toc, related, search] 
    show_powered_by: false 

markdown_extensions:
    - toc:
        permalink: "Â¶"

