site_name: conficus 

pages:
    - Home: index.md
    - Features: 
        - coercion.md
        - Nested Sections: nested-sections.md
        - inheritance.md

site_url: http://thebitsilo.com/dev/conficus/current
repo_url: https://bitbucket.org/mgemmill/conficus
site_description: INI configuration library
site_author: Mark Gemmill
copyright: 2017 Mark Gemmill
use_directory_urls: true

theme: alabaster

theme_dir: custom_theme

extra_css:
    - css/highlight.css

extra_javascript:
    - js/highlight.pack.js

extra:
    logo_name: foo
    logo_title: foo-title
    extra_nav_links:   
        Bitbucket: https://bitbucket.org/mgemmill/conficus
    homepage_sidebars: [about, toc, related, search] 
    show_powered_by: false 

markdown_extensions:
    - toc:
        permalink: "Â¶"

